/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gutiérrez
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NUM1 = new javax.swing.JTextField();
        NUM2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(223, 255, 108));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Búsqueda Avanzada");

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Generar Estadísticas");

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("Información del programa");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese  número de afiliciación IMSS");

        NUM1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NUM1.setText("XXXX-XX-XXXX-X XXXXXXXX");
        NUM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NUM1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NUM1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NUM1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NUM1MouseReleased(evt);
            }
        });
        NUM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM1ActionPerformed(evt);
            }
        });

        NUM2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NUM2.setText("XXXX-XX-XXXX-X XXXXXXXX");
        NUM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUM2MouseClicked(evt);
            }
        });
        NUM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUM2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Compruebe");

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setText("Ir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("_____________________________________");

        jButton5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton5.setText("Cerrar Sesión");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NUM1)
                    .addComponent(NUM2)
                    .addComponent(jLabel2)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NUM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NUM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NUM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUM2ActionPerformed

    private void NUM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUM1ActionPerformed
        
    }//GEN-LAST:event_NUM1ActionPerformed

    private void NUM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM1MouseClicked
        if(NUM1.getText().equals("XXXX-XX-XXXX-X XXXXXXXX")){
        NUM1.setText("");
        }
        if(NUM2.getText().equals("")){
        NUM2.setText("XXXX-XX-XXXX-X XXXXXXXX");
        }
    }//GEN-LAST:event_NUM1MouseClicked

    private void NUM1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM1MouseReleased
        
    }//GEN-LAST:event_NUM1MouseReleased

    private void NUM1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM1MouseExited
        
    }//GEN-LAST:event_NUM1MouseExited

    private void NUM1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM1MouseEntered
        
    }//GEN-LAST:event_NUM1MouseEntered

    private void NUM1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM1MousePressed
        
    }//GEN-LAST:event_NUM1MousePressed

    private void NUM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUM2MouseClicked
        if(NUM2.getText().equals("XXXX-XX-XXXX-X XXXXXXXX")){
        NUM2.setText("");
        }
        if(NUM1.getText().equals("")){
        NUM1.setText("XXXX-XX-XXXX-X XXXXXXXX");
        }
    }//GEN-LAST:event_NUM2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String d;
        if(NUM1.getText().equals("")){
            javax.swing.JOptionPane.showMessageDialog(null,"Complete el llenado del número de afiliación","",0);
            return;
        }
        if(NUM2.getText().equals("")){
            javax.swing.JOptionPane.showMessageDialog(null,"Complete el llenado del número de afiliación comprobación","",0);
            return;
        }
        String [] nmr = NUM1.getText().split("");
        //javax.swing.JOptionPane.showMessageDialog(null,nmr);
        if(nmr.length<22){
            javax.swing.JOptionPane.showMessageDialog(null,"El número le faltan dígitos","",0);
            return;
        }
        if(nmr.length>22){
            javax.swing.JOptionPane.showMessageDialog(null,"El número tiene dígitos de más","",0);
            return;
        }
        
        if(!nmr[4].equals("-") && !nmr[7].equals("-") && !nmr[12].equals("-")){
            javax.swing.JOptionPane.showMessageDialog(null,"Le falta(n) '-' al número ","",0);
            return;
        }
        
        if(NUM1.getText().equals(NUM2.getText())){
            dispose();
            IR c = new IR();
            c.setVisible(true);
            d=NUM2.getText();
            IR.naf.setText(d);
        }
        else javax.swing.JOptionPane.showMessageDialog(null,"Los campos no coinciden","",0);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
            Login c = new Login();
            c.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NUM1;
    public static javax.swing.JTextField NUM2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
